using Pharmacy_System.DTOs.Category;
using Pharmacy_System.Modules;
using Pharmacy_System.Repos;

namespace Pharmacy_System.Services
{
    public class CategoryService
    {
        // Used to access data from the database
        private readonly CategoryRepo categoryRepo;

        public CategoryService(CategoryRepo categoryRepo)
        {
            this.categoryRepo = categoryRepo;
        }

        // Returns all categories as DTOs
        public async Task<List<CategoryDto>> GetAllCategories()
        {
            List<Category> categories = await categoryRepo.GetAllCategories();
               

            // Create an empty list for the response
            List<CategoryDto> categoryDtos = new List<CategoryDto>();
               

            // Convert each Category model into CategoryDto
            foreach (Category category in categories)
            {
                CategoryDto dto = ConvertToDto(category);
                categoryDtos.Add(dto);
            }

            return categoryDtos;
        }

        // Returns one category using its ID
        public async Task<CategoryDto?> GetCategoryById(int id)
        {
            // Search for the category
            Category? category =
                await categoryRepo.GetCategoryById(id);

            // Return null if category does not exist
            if (category == null)
            {
                return null;
            }

            // Convert the model into DTO
            return ConvertToDto(category);
        }

        // Creates a new category
        // Returns the generated category ID
        public async Task<int> CreateCategory(CreateCategoryDto dto)
            
        {
            // Remove spaces from the beginning and end
            string categoryName = dto.CategoryName.Trim();

            // Check if another category already has the same name
            Category? existingCategory =await categoryRepo.GetCategoryByName(categoryName);
                

            if (existingCategory != null)
            {
                throw new Exception( "Category name already exists");
                   
                
            }

            // Create a new Category model
            Category category = new Category
            {
                CategoryName = categoryName,
                Description = dto.Description?.Trim()
            };

            // Save the category in the database
            await categoryRepo.Add(category);

            // Return the ID generated by the database
            return category.CategoryID;
        }

        // Updates an existing category
        public async Task<bool> UpdateCategory(
            int id,
            UpdateCategoryDto dto)
        {
            // Find the category that will be updated
            Category? category =await categoryRepo.GetCategoryById(id);
                

            if (category == null)
            {
                return false;
            }

            string categoryName = dto.CategoryName.Trim();

            // Search for another category with the same name
            Category? existingCategory = await categoryRepo.GetCategoryByName(categoryName);
               

            // Prevent duplicate names
            // Allow the current category to keep its own name
            if (existingCategory != null &&existingCategory.CategoryID != id)
                
            {
                throw new Exception("Category name already exists" );
                    
               
            }

            // Update the model values
            category.CategoryName = categoryName;
            category.Description = dto.Description?.Trim();

            // Save changes
            await categoryRepo.CategoryUpdate();

            return true;
        }

        
        // Converts Category model into CategoryDto
        private CategoryDto ConvertToDto(Category category)
        {
            CategoryDto dto = new CategoryDto
            {
                CategoryID = category.CategoryID,
                CategoryName = category.CategoryName,
                Description = category.Description
            };

            return dto;
        }
    }
}