using Pharmacy_System.DTOs.Supply;
using Pharmacy_System.Modules;
using Pharmacy_System.Repos;

namespace Pharmacy_System.Services
{
    public class SupplyService
    {
        // Repository used to manage  data in the database
        private readonly SupplyRepo supplyRepo;

        private readonly SupplierRepo supplierRepo;

        private readonly MedicineRepo medicineRepo;

        private readonly WarehouseRepo warehouseRepo;

      
        public SupplyService(
            SupplyRepo supplyRepo,
            SupplierRepo supplierRepo,
            MedicineRepo medicineRepo,
            WarehouseRepo warehouseRepo)
        {
            this.supplyRepo = supplyRepo;
            this.supplierRepo = supplierRepo;
            this.medicineRepo = medicineRepo;
            this.warehouseRepo = warehouseRepo;
        }

        // Gets all supplies from the repository
        // Then converts every Supply model into SupplyDto
        public async Task<List<SupplyDto>> GetAllSupplies()
        {
            // Get all supply records from the database
            List<Supply> supplies = await supplyRepo.GetAllSupply();
               

            // Create an empty list for the response DTOs
            List<SupplyDto> supplyDtos = new List<SupplyDto>();
               

            // Convert each Supply model into SupplyDto
            foreach (Supply supply in supplies)
            {
                SupplyDto dto = ConvertToDto(supply);
                supplyDtos.Add(dto);
            }

            // Return the list to the Controller
            return supplyDtos;
        }

        // Gets one supply using its ID
        public async Task<SupplyDto?> GetSupplyById(int id)
        {
            // Search for the supply in the database
            Supply? supply =await supplyRepo.GetSupplyById(id);
                

            // Return null if the supply does not exist
            if (supply == null)
            {
                return null;
            }

            // Convert the Supply model into SupplyDto
            return ConvertToDto(supply);
        }

        // Creates a new supply
        public async Task<int> CreateSupply(CreateSupplyDto dto)
        {
            // Check that the supplier exists
            Supplier? supplier =await supplierRepo.GetSupplierById(dto.SupplierID);
                

            if (supplier == null)
            {
                throw new Exception("Supplier not found");
            }

            // Check that the medicine exists
            Medicine? medicine =await medicineRepo.GetMedicineById(dto.MedicineID);
                

            if (medicine == null)
            {
                throw new Exception("Medicine not found");
            }

            // Check that the warehouse exists
            Warehouse? warehouse =await warehouseRepo.GetWarehouseById(dto.WarehouseID);
                

            if (warehouse == null)
            {
                throw new Exception("Warehouse not found");
            }

            // Check that the expiry date was provided
            if (dto.ExpiryDate == null)
            {
                throw new Exception("Expiry date is required");
            }

            // Prevent adding expired medicine
            // The expiry date must be after today's date
            if (dto.ExpiryDate.Value.Date <= DateTime.Today)
            {
                throw new Exception("Expiry date must be later than today");
                
                    
            }

            // Create a new Supply model
            Supply supply = new Supply();

            // Copy input data from CreateSupplyDto to Supply model
            supply.BatchNumber = dto.BatchNumber;
            supply.Quantity = dto.Quantity;
            supply.UnitCost = dto.UnitCost;

            // Business rule:
            // Total cost is calculated by the system
            // TotalCost = Quantity × UnitCost
            supply.TotalCost =dto.Quantity * dto.UnitCost;
                

            // SupplyDate is generated by the system
            supply.SupplyDate = DateTime.Now;

            // ExpiryDate comes from the user input
            supply.ExpiryDate = dto.ExpiryDate.Value;

            // Store the related foreign keys
            supply.SupplierID = dto.SupplierID;
            supply.MedicineID = dto.MedicineID;
            supply.WarehouseID = dto.WarehouseID;

            // Send the new Supply model to the repository
            // The repository adds it to the database
            await supplyRepo.Add(supply);

            // Return the ID generated by the database
            return supply.SupplyId;
        }

        // Updates an existing supply
        // Returns true when successful
        // Returns false when the supply is not found
        public async Task<bool> UpdateSupply(
            int id,
            UpdateSupplyDto dto)
        {
            // Find the existing supply
            Supply? supply =
                await supplyRepo.GetSupplyById(id);

            // Stop if the supply does not exist
            if (supply == null)
            {
                return false;
            }

            // Check that the new supplier exists
            Supplier? supplier =await supplierRepo.GetSupplierById(dto.SupplierID);
                

            if (supplier == null)
            {
                throw new Exception("Supplier not found");
            }

            // Check that the new medicine exists
            Medicine? medicine =await medicineRepo.GetMedicineById(dto.MedicineID);
                

            if (medicine == null)
            {
                throw new Exception("Medicine not found");
            }

            // Check that the new warehouse exists
            Warehouse? warehouse =await warehouseRepo.GetWarehouseById(dto.WarehouseID);
                

            if (warehouse == null)
            {
                throw new Exception("Warehouse not found");
            }

            // Check that the expiry date was provided
            if (dto.ExpiryDate == null)
            {
                throw new Exception("Expiry date is required");
            }

            // Prevent updating the supply with an expired date
            if (dto.ExpiryDate.Value.Date <= DateTime.Today)
            {
                throw new Exception("Expiry date must be later than today");
                    
                
            }

            // Update the Supply model properties
            supply.BatchNumber = dto.BatchNumber;
            supply.Quantity = dto.Quantity;
            supply.UnitCost = dto.UnitCost;

            // Recalculate the total cost after the update
            supply.TotalCost =dto.Quantity * dto.UnitCost;
                

            // Update expiry date and foreign keys
            supply.ExpiryDate = dto.ExpiryDate.Value;
            supply.SupplierID = dto.SupplierID;
            supply.MedicineID = dto.MedicineID;
            supply.WarehouseID = dto.WarehouseID;

            // Save the changes in the database
            await supplyRepo.SupplyUpdate();

            
            return true;
        }

        

        // Converts the Supply model into SupplyDto
        // This method prepares the data returned by the API
        private SupplyDto ConvertToDto(Supply supply)
        {
            // Create an empty response DTO
            SupplyDto dto = new SupplyDto();

            // Copy the main Supply information
            dto.SupplyId = supply.SupplyId;
            dto.BatchNumber = supply.BatchNumber;
            dto.Quantity = supply.Quantity;
            dto.UnitCost = supply.UnitCost;
            dto.TotalCost = supply.TotalCost;
            dto.SupplyDate = supply.SupplyDate;
            dto.ExpiryDate = supply.ExpiryDate;

            // Copy Supplier information
            dto.SupplierID = supply.SupplierID;
            dto.FullName = supply.Supplier.FullName;

            // Copy Medicine information
            dto.MedicineID = supply.MedicineID;
            dto.MedicineName =
                supply.Medicine.MedicineName;

            // Copy Warehouse information
            dto.WarehouseID = supply.WarehouseID;
            dto.Location = supply.Warehouse.Location;

            // Return the completed DTO
            return dto;
        }
    }
}