namespace Pharmacy_System.DTOs.Supply
{
    // Used to return supply information from the API
    public class SupplyDto
    {
        // Supply ID generated by the system
        public int SupplyId { get; set; }

        // Batch number of the supply
        public string BatchNumber { get; set; } = string.Empty;

        // Quantity of medicine supplied
        public int Quantity { get; set; }

        // Total cost of the supply
        public decimal TotalCost { get; set; }

        // Date when the supply was created
        public DateTime SupplyDate { get; set; }

        // Expiry date of the supplied medicine
        public DateTime ExpiryDate { get; set; }

        // Supplier foreign key
        public int SupplierId { get; set; }

        // Supplier name displayed in the response
        public string SupplierName { get; set; } = string.Empty;

        // Medicine foreign key
        public int MedicineId { get; set; }

        // Medicine name displayed in the response
        public string MedicineName { get; set; } = string.Empty;

        // Warehouse foreign key
        public int WarehouseId { get; set; }
    }
}