namespace Pharmacy_System.DTOs.Transfer
{
    // Used to return shipment information from the API
    public class TransferDto
    {
        //  generated by the system
        public int TransferId { get; set; }

        // ID of the warehouse sending the shipment
        public int WarehouseId { get; set; }

        // ID of  pharmacy receiving the shipment
        public int PharmacyId { get; set; }

        // Date when  shipment created
        public DateTime TransferDate { get; set; }

        // Date when shipment received
        public DateTime? ReceiveDate { get; set; }

        // Current shipment status
        public string Status { get; set; } = string.Empty;

        // IDs of medicines included in  shipment
        public List<int> MedicineIds { get; set; } =new List<int>();
            

        // Names of medicines included in  shipment
        public List<string> MedicineNames { get; set; } = new List<string>();
           
    }
}