using Pharmacy_System.DTOs.CustomerOrderDetail;

namespace Pharmacy_System.DTOs.CustomerOrder
{
    // Used to return complete customer order information
    public class CustomerOrderDto
    {
        // Generated by the database
        public int CustomerOrderId { get; set; }

        // Customer information
        public int CustomerID { get; set; }
        public string FullName { get; set; } = string.Empty;

        // Pharmacy information
        public int PharmacyID { get; set; }
        public string PharmacyName { get; set; } = string.Empty;

 
        public DateTime OrderDate { get; set; }

   
        public decimal TotalCost { get; set; }

      
        public string Status { get; set; } = string.Empty;

        // Medicines included in the order
        public List<CustomerOrderDetailDto> OrderDetails { get; set; }= new List<CustomerOrderDetailDto>();
            
    }
}